language:
  - ruby
  
before_script:
 - cd JBB-Web/
 - gem install rspec rspec-rails simplecov
 - bundle install

script:
  - rake db:migrate RAILS_ENV=test
  
rvm:
  - 2.3.1
  
sudo: required 

notifications:
  email:
    recipients:
      - danieelteles@gmail.com
