language:
  - ruby
  
rvm:
  - 2.3.1

notifications:
  email:
    recipients:
      - danieelteles@gmail.com
      - adailson2@gmail.com
      - gustavomn93@gmail.com
      - nicacionetobsb@gmail.com
      - iamferreirajp@gmail.com
