language: ruby
cache:
  bundler: true
  directories:
    - tmp/cache/assets/test/sprockets

rvm:
  - "2.3.1"

addons:
  postgresql: "9.5.4"

before_script:
 - sudo service postgresql start
 - cd JBB-Web/
 - gem install bundler
 - gem install rspec rspec-rails simplecov codeclimate-test-reporter
 - bundle install

script:
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rspec spec

after_success:
  - CODECLIMATE_REPO_TOKEN=cb4ea7ac2d81c8fe078ceb548d4a19ddcaef0761731ef87525777e4a3ad62044 bundle exec rake

notifications:
  email:
    recipients:
      - danieelteles@gmail.com
      - adailson2@gmail.com
      - gustavomn93@gmail.com
      - nicacionetobsb@gmail.com
      - iamferreirajp@gmail.com
