language: ruby
cache: bundler

rvm:
  - "2.3.1"

addons:
  postgresql: "9.5.4"

script: "RAILS_ENV=test bundle exec rake"

before_script:
 - sudo service postgresql start
 - cd JBB-Web/
 - gem install rspec rspec-rails simplecov
 - bundle install
 - rake db:setup
bundler_args: --binstubs=./bundler_stubs

sudo: required

after_success:
  - CODECLIMATE_REPO_TOKEN=cb4ea7ac2d81c8fe078ceb548d4a19ddcaef0761731ef87525777e4a3ad62044 bundle exec rake 

notifications:
  email:
    recipients:
      - danieelteles@gmail.com
      - adailson2@gmail.com
      - gustavomn93@gmail.com
      - nicacionetobsb@gmail.com
      - iamferreirajp@gmail.com
