default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: JBB_Web_development
  username: travis
  password:

test:
  <<: *default
  database: travis_ci_test
  username: travis
  password:

production:
  <<: *default
  database: JBB_Web_production
  username: travis
  password: <%= ENV['JBB_WEB_DATABASE_PASSWORD'] %>
