default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: travis
  password: jbbweb123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: JBB_Web_development
  username: travis
  password: jbbweb123

test:
  <<: *default
  database: JBB_Web_test
  username: travis
  password: jbbweb123

production:
  <<: *default
  database: JBB_Web_production
  username: JBB_Web
  password: <%= ENV['JBB_WEB_DATABASE_PASSWORD'] %>
